In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.model_selection import KFold

In [2]:
import xgboost as xgb

In [3]:
df_anime = pd.read_csv('output_data_anime.csv')
df_anime = df_anime.drop(df_anime.columns[0], axis=1)

In [4]:
df_anime

,Title,Rating,genre_Action,genre_Adventure,genre_Cars,genre_Comedy,genre_Dementia,genre_Demons,genre_Drama,genre_Ecchi,...,studio_ixtl,studio_teamKG,studio_ufotable,studio_unknown,type_Movie,type_Music,type_ONA,type_OVA,type_Special,type_TV
0,0.513510,8.81,1,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
1,0.461968,8.41,1,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
2,0.355224,8.31,1,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
3,0.896079,7.34,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
4,0.633831,7.04,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9981,0.488208,6.89,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
9982,0.489538,5.69,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
9983,0.159521,8.29,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
9984,0.609244,7.45,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
9985,0.504010,6.30,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [5]:
X = df_anime.drop('Rating', axis=1).values
y = df_anime['Rating'].values

In [6]:
df_anime

,Title,Rating,genre_Action,genre_Adventure,genre_Cars,genre_Comedy,genre_Dementia,genre_Demons,genre_Drama,genre_Ecchi,...,studio_ixtl,studio_teamKG,studio_ufotable,studio_unknown,type_Movie,type_Music,type_ONA,type_OVA,type_Special,type_TV
0,0.513510,8.81,1,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
1,0.461968,8.41,1,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
2,0.355224,8.31,1,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
3,0.896079,7.34,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
4,0.633831,7.04,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9981,0.488208,6.89,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
9982,0.489538,5.69,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
9983,0.159521,8.29,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
9984,0.609244,7.45,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
9985,0.504010,6.30,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
df_anime

,Title,Rating,genre_Action,genre_Adventure,genre_Cars,genre_Comedy,genre_Dementia,genre_Demons,genre_Drama,genre_Ecchi,...,studio_ixtl,studio_teamKG,studio_ufotable,studio_unknown,type_Movie,type_Music,type_ONA,type_OVA,type_Special,type_TV
0,0.513510,8.81,1,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
1,0.461968,8.41,1,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
2,0.355224,8.31,1,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
3,0.896079,7.34,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
4,0.633831,7.04,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9981,0.488208,6.89,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
9982,0.489538,5.69,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
9983,0.159521,8.29,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
9984,0.609244,7.45,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
9985,0.504010,6.30,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [9]:
reg_xgb = xgb.XGBRegressor(random_state=42)
reg_xgb.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=42, ...)

In [10]:
y_test_pred = reg_xgb.predict(X_test)

In [11]:
from sklearn.metrics import mean_squared_error

In [12]:
mean_squared_error(y_test, y_test_pred)

0.46043777100543376

In [13]:
from sklearn.metrics import r2_score

In [14]:
print(r2_score(y_test, y_test_pred))

0.5502546460378128

In [15]:
for i in range(10):
    print(y_test[i], y_test_pred[i])

6.52 6.595587
6.08 6.5061355
6.16 5.7605324
6.98 7.600794
7.21 7.442676
6.84 6.5175996
7.79 7.1332293
7.16 7.095503
5.33 6.5546308
6.31 6.5530252

In [16]:
import pickle
filename = "model_xgb.pkl"

pickle.dump(reg_xgb, open(filename, "wb"))